resources:
  - name: myIWH
    type: IncomingWebhook
    configuration:
      webhookName: MyIncomingWebhookIntegration

pipelines:
  - name: basic_pipeline
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: myIWH
        execution:
          onExecute:
            - echo "$res_myIWH_payload" | jq '.' > payload.json
            - |
              add_run_variables my_payload="$(jq -n \
              --arg pr $(read_json payload.json "project") \
              --arg st $(read_json payload.json "stage") \
              --arg sv $(read_json payload.json "service") \
              --arg sh $(read_json payload.json "shkeptncontext") \
              --arg id $(read_json payload.json "id") \
              '{ \
               data:{project:$pr,stage:$st,service:$sv,status:"succeeded",result:"pass"}, \
               source:"cas-quickstart", \
               specversion:"1.0", \
               type:"sh.keptn.event.mytask-interactive.finished", \
               shkeptncontext:$sh,triggeredid:$id \
              }')"
            - echo "$my_payload"
      - name: step_2
        type: Bash
        configuration:
          inputSteps:
            - name: step_1
        execution:
          onExecute:
            - 'curl -X POST "https://pye55831.cloudautomation.live.dynatrace.com/api/v1/event" -H "accept: application/json" -H "x-token: OUvGHNDLQm4LVxiawg1EvSlbDPT98MBbztBpLHZ4LPXzR" -H "Content-Type: application/json" -d "$my_payload"'
