resources:
  - name: myOWH
    type: OutgoingWebhook
    configuration:
      webhookName: MyOutgoingWebhookIntegration
      path: /url
      headers:
        content-type: application/x-www-form-urlencoded
  - name: myIWH
    type: IncomingWebhook
    configuration:
      webhookName: MyIncomingWebhookIntegration

pipelines:
  - name: basic_pipeline
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: myIWH
        execution:
          onExecute:
            - echo "$res_myIWH_payload" | jq '.' > payload.json
            - echo "$res_myIWH_payload"
            - add_run_variables project=$(read_json payload.json "project")
            - add_run_variables stage=$(read_json payload.json "stage")
            - add_run_variables service=$(read_json payload.json "service")
            - add_run_variables shkeptncontext=$(read_json payload.json "shkeptncontext")
            - add_run_variables id=$(read_json payload.json "id")
            - |+
            JSON_STRING=$(jq -n \
            --arg bn $(read_json payload.json "project") --arg on $(read_json payload.json "stage") --arg tl $(read_json payload.json "service") '{bucketname:$bn, objectname:$on, targetlocation:$tl}')
            - echo $JSON_STRING
            - add_run_variables my_payload=$(cat << {"data":{"project":"$project","stage":"$stage","service":"$service","status":"succeeded","result":"pass"},"source":"cas-quickstart","specversion":"1.0","type":"sh.keptn.event.mytask-interactive.finished","shkeptncontext":"$shkeptncontext","triggeredid":"$id"})
            - echo $my_payload
            - echo $JSON_STRING
      - name: step_2
        type: Bash
        configuration:
          inputSteps:
            - name: step_1
          outputResources:
            - name: myOWH
          integrations:
            - name: my_github
        execution:
          onExecute:
            - 'curl -H "Authorization: token ${int_my_github_token}" ${int_my_github_url}/rate_limit'
            - 'curl -X POST "https://pye55831.cloudautomation.live.dynatrace.com/api/v1/event" -H "accept: application/json" -H "x-token: OUvGHNDLQm4LVxiawg1EvSlbDPT98MBbztBpLHZ4LPXzR" -H "Content-Type: application/json" -d "$my_payload"'
            - formUrlEncodedPayload="foo=bar&runNumber=$run_number&stepName=$step_name"
            - set_payload myOWH "$formUrlEncodedPayload"
